#!/usr/bin/env python3
"""The writing guard's detectors: three mechanisms the user named, one file.

    python3 writing_guard_detectors.py <file> [--mono-title]

WHERE THESE MECHANISMS COME FROM
--------------------------------
Two pre-registered labeling rounds (51 answered items, 2026-08-21) produced
three mechanisms in the user's own words, recorded in the initiative's
`sweep/ROUND1-READOUT.md` and validated at n=1 in `sweep/ROUND2-ANALYSIS.md`:

  opening_referent      first lines that do not establish who, what or where
                        ("what instance? what 'still'? 'returning' to what?")
  front_loaded_framing   an abstract framing phrase ahead of the point
                        ("I've read 6 words, yet I have no idea what the
                        sentence is about ... I hate this recursive sentence
                        structure")
  positional_aphorism   the "[X], not [Y]" shape in a title
                        ("completely unaccaptable stuff")

The code is vendored from that initiative's round-2 prototypes
(`sweep/round2-prototypes/{opening_referent,front_loaded_framing,
positional_aphorism,_proto_shared}.py`), which in turn copied their prose
segmentation from the 2026-08-15 linter's `proto/extract_prose.py` and their
definite-opacity detector from the frozen `sweep/reference-impl/_shared.py`.
Vendored rather than imported: a hook runs on a user's machine with nothing but
python3, and it must keep producing the same verdicts when the research tree
moves. Standard library only, for the same reason.

TWO FIXES THE ROUND-2 LABELS FORCED, AND ONE THEY DID NOT
---------------------------------------------------------
1. The E3 postnominal exemption is suspended inside the opening window. The
   frozen detector exempts a definite phrase when a preposition follows its
   noun, which is why "The instance still froze on returning..." - the phrase
   the user quoted twice as their reason for rejecting a text - was invisible
   to it. ROUND2-ANALYSIS.md F.2. Both readings are computed, because which one
   may block is decided by false-positive validation, not by this file.
2. A definite phrase closed by a colon is reported, so that "The result: ..."
   is not scored zero. The user flagged that span; the frozen shape test missed
   it because "result" is not an abstract head. ROUND2-ANALYSIS.md F.4. It is
   advisory-only: the fix was never pre-registered, so it has no standing to
   block anything.
3. NOT fixed: the two head-boundary parser defects named in ROUND2-ANALYSIS.md
   F.4 ("the 202 user turns that followed them" read as "that followed").
   Repairing a parser while looking at the three texts it must stay quiet on is
   how a detector gets fitted to three labels. The defect instead does what it
   should: it makes the whole-window count fire on accepted writing, and the
   validation harness disqualifies that count from blocking.

TIERS
-----
Only signals listed in BLOCKING_SIGNALS below may deny a tool call, and that
tuple is generated by `tests/writing-guard-fp-validation.py` from the texts the
user accepted - never computed here at run time. Every other signal is
advisory: recorded in a bypass entry, reported by the harness, never a block.
"""
import html as html_mod
import json
import re
import sys

# ============================================================ prose extraction
# Verbatim from the 2026-08-15 tool's proto/extract_prose.py, by way of the
# frozen sweep/reference-impl/_shared.py. Every mechanism reads the same
# segmentation, so "the first sentence" means one thing across the file.
BLOCK_TAGS = ['p', 'li', 'td', 'th', 'h1', 'h2', 'h3', 'summary', 'title',
              'br', 'tr', 'div', 'section', 'details', 'ol', 'ul', 'table',
              'thead', 'tbody', 'header', 'main']
SENT_SPLIT = re.compile(r'(?<=[.!?])\s+(?=[A-Z0-9“(])')
WORD_RE = re.compile(r'[A-Za-z0-9]')


def _mask_quotes(text):
    """Curly-quoted passages are someone else's words; mask them out."""
    quotes = re.findall(r'“(.*?)”', text, flags=re.S)
    masked = re.sub(r'“.*?”', ' “QUOTE” ', text, flags=re.S)
    return masked, quotes


def blocks_from_html(src):
    src = re.sub(r'<!--.*?-->', ' ', src, flags=re.S)
    src = re.sub(r'<style>.*?</style>', ' ', src, flags=re.S)
    src = re.sub(r'<script.*?</script>', ' ', src, flags=re.S)
    src = re.sub(r'<svg.*?</svg>', ' ', src, flags=re.S)
    src = re.sub(r'<span class="path">.*?</span>', ' «PATH» ', src, flags=re.S)
    src = re.sub(r'<span class="numname">.*?</span>', ' «ID» ', src, flags=re.S)
    src = re.sub(r'<(?:pre|code|blockquote)[^>]*>.*?</(?:pre|code|blockquote)>',
                 ' ', src, flags=re.S)
    for tag in BLOCK_TAGS:
        src = re.sub(r'</?%s[^>]*>' % tag, '\n@@B@@\n', src)
    src = re.sub(r'<[^>]+>', ' ', src)
    src = html_mod.unescape(src)
    out = []
    for b in src.split('@@B@@'):
        b = re.sub(r'\s+', ' ', b).strip()
        if re.search(r'[A-Za-z]', b):
            out.append(b)
    return out


def blocks_from_markdown(src):
    src = re.sub(r'^```.*?^```', ' ', src, flags=re.S | re.M)   # fenced code
    src = re.sub(r'^(?: {4}|\t).*$', ' ', src, flags=re.M)      # indented code
    src = re.sub(r'`[^`]+`', ' «CODE» ', src)                   # inline code
    src = re.sub(r'https?://\S+', ' «URL» ', src)
    src = re.sub(r'(?<![\w])(~?/[\w.\-/]+/[\w.\-/]+)', ' «PATH» ', src)
    src = re.sub(r'^#+\s*', '', src, flags=re.M)
    src = re.sub(r'^[=\-]{3,}\s*$', '\n\n', src, flags=re.M)
    src = re.sub(r'\*\*([^*]+)\*\*', r'\1', src)
    src = re.sub(r'(?<!\w)\*([^*\n]+)\*(?!\w)', r'\1', src)
    out = []
    for para in re.split(r'\n\s*\n', src):
        for piece in re.split(r'\n(?=\s*(?:[-*+]|\d+\.)\s)', para):
            piece = re.sub(r'^\s*(?:[-*+]|\d+\.)\s+', '', piece.strip())
            piece = re.sub(r'\s+', ' ', piece).strip()
            if re.search(r'[A-Za-z]', piece):
                out.append(piece)
    return out


def extract_text(src, is_html=False):
    """The document as prose: blocks, then sentences, quotes masked.

    The prototypes read a path. A hook also reads commit messages, which were
    never files, so the source string is the parameter here. Nothing else about
    the extraction changed.
    """
    raw_blocks = blocks_from_html(src) if is_html else blocks_from_markdown(src)
    blocks, all_quotes = [], []
    for b in raw_blocks:
        masked, quotes = _mask_quotes(b)
        all_quotes.extend(quotes)
        blocks.append(masked)
    sentences = []
    for i, b in enumerate(blocks):
        for s in SENT_SPLIT.split(b):
            s = s.strip()
            if re.search(r'[A-Za-z]', s):
                sentences.append((i, s))

    def wc(t):
        return len([w for w in re.split(r'\s+', t)
                    if WORD_RE.search(w) and not w.startswith('«')])
    return {'blocks': blocks, 'sentences': sentences,
            'words': sum(wc(b) for b in blocks), 'quotes': all_quotes,
            'raw': src}


# =================================================================== wordlists
# STOPWORDS and AUX_VERBS from the 2026-08-15 wordlists.py; VERB_FORMS is its
# 342-entry list. The head-boundary rule below is built out of all three, so
# they must not drift from the frozen copies.
STOPWORDS = set("""a about above after again against all also am an and any are
as at be because been before being below between both but by can could did do
does don down during each few for from had has have he her here his how i if in
into is it its just may me might more most must my no nor not now of on once
only or other our out over own s same shall she should so some such t than that
the their them then there these they this those through to too under until up
very was we were what when where which while who whom whose why will with would
yet you your""".split())

AUX_VERBS = set("""am are be been being can could did do does had has have is
may might must shall should was were will would""".split())

VERB_FORMS = set("""add adds am appear appears apply applys are ask asks ate be been began
begun being believe believes bent bought bring brings broke broken brought
build builds built burnt buy buys call calls came can carry carrys catch
catches catchs caught change changes check checks chose chosen come comes
confirm confirms consider considers continue continues cost costs could
count counts create creates cut cuts dealt detect detects did die dies do
does done drawn drew driven drop drops drove eaten exceed exceeds exempt
exempts expect expects fail fails fallen feel feels fell felt find finds
fire fires fix fixes fixs flag flags flew follow follows forgotten fought
found frozen gave get gets give given gives go gone gos got grew had
happen happens has have heard held help helps hidden hit hold holds hung
include includes is keep keeps kept kill kills knew know known knows laid
lay lead leads learn learns learnt leave leaves led left lent let lie lies
live lives load loads look looks lost made make makes match matches matchs
may mean means meant measure measures met might miss misses misss move
moves must name names need needs note notes occur occurs offer offers open
opens paid parse parses pass passes passs play plays print prints put
raise raises ran rank ranks reach reaches reachs read reads remember
remembers report reports ridden risen rose run runs said sang sank sat saw
say says score scores see seem seems seen sees send sends sent serve
serves set shall ship ships should show shown shows shut sit sits sneak
sneaks sold sort sorts sought speak speaks spent spoke spoken spread stand
stands start starts state states stay stays stolen stood stop stops struck
stuck sung suppress suppresses suppresss swam swept sworn swum swung take
taken takes talk talks taught tell tells test tests think thinks thought
threw thrown told took turn turns understand understands use uses walk
walks want wants was watch watches watchs went were will win wins woken
won wore work works worn would write writes written wrote""".split())

# From the sweep's NEW-A5 vocabulary (make_vectors.py), copied by the round-2
# prototypes: who counts as somebody a reader can picture.
FIRST_SECOND = set('i we you my our your me us mine ours yours'.split())
ROLE_NOUNS = set("""agent reviewer author user orchestrator executor judge
tool script test harness model linter checker writer reader editor team
engineer developer maintainer researcher operator owner client server
compiler parser runner scheduler worker assistant bot person people
committee board panel arm rewriter""".split())
NOMINAL_SUFFIX = ('tion', 'sion', 'ment', 'ance', 'ence', 'ity', 'ness', 'ism')

# Abstract heads English spells without a suffix; the suffixed ones
# (escalation, containment, granularity) are caught by NOMINAL_SUFFIX. Written
# 2026-08-21 from the mechanism's description, never selected against a label.
ABSTRACT_HEADS = set("""logic reasoning rationale framing frame framework
approach context structure dynamics implications strategy principle principles
basis scope aspect aspects factor factors criteria criterion methodology
semantics taxonomy topology ontology philosophy premise premises thesis theory
hierarchy tradeoff tradeoffs lifecycle invariant invariants posture stance
protocol doctrine discipline ordering sequencing handling threshold thresholds
boundary boundaries layering coupling""".split())

# The words a sentence starts with when something is put in front of its
# subject.
SUBORDINATORS = set("""after although as because before despite given if once
provided since though unless until when whenever where whereas wherever while
whilst""".split())
FRONTING_PREPOSITIONS = set("""about above across against along amid among
around at before behind below beneath beside besides between beyond by during
except for from in inside into near of off on onto outside over past through
throughout to toward towards under underneath until up upon via with within
without""".split())

PRONOUN_LEG = set('it they them he him she itself themselves'.split())
DEMONSTRATIVES = set('this that these those'.split())
DUMMY_IT_ADJ_SUFFIX = ('able', 'ible', 'ive', 'ous', 'ary', 'ent', 'ant',
                       'ful', 'ic', 'al')
DUMMY_IT_ADJ = set("""clear hard easy possible likely important true false
obvious worth common rare odd fair safe wrong right best worse better
tempting hopeless""".split())

BARE_DEMONSTRATIVE = re.compile(
    r'^(?:This|That|These|Those|It)\s+'
    r'(?:is|are|was|were|means|matters|requires|makes|holds|shows|keeps|'
    r'turns|works|fails|costs|counts|stands|depends|explains|proves|remains)\b')
ANTECEDENT_NP = re.compile(
    r"\b(?:a|an|the|its|their|this|that|these|those|his|her|our|some|any|"
    r"each|every|another|new|one|two|three)\s+[a-z][a-z'-]{2,}", re.I)
PROPER_NAME = re.compile(r'(?<!^)\b[A-Z][a-z]{2,}')

# A commit body labels its sections [PROBLEM] / [ROOT-CAUSE] / [CHANGE]. The
# label is structure, not authored prose, so shape tests read without it.
SECTION_LABEL = re.compile(r'^\s*\[[A-Z][A-Z0-9\- ]*\]\s*')
ATX_HEADING = re.compile(r'^\s{0,3}(#{1,6})\s+(\S.*?)\s*#*\s*$')
HTML_TITLE = re.compile(r'<title[^>]*>(.*?)</title>', re.S | re.I)
HTML_HEADING = re.compile(r'<h([1-6])[^>]*>(.*?)</h\1>', re.S | re.I)


def strip_section_label(sentence):
    return SECTION_LABEL.sub('', sentence)


def words(text):
    return [w for w in text.split()
            if WORD_RE.search(w) and not w.startswith('«')]


def tok(word):
    return word.strip('.,;:!?()[]{}"\'—“”‘’`').lower()


def first_finite_verb(tokens):
    for n, w in enumerate(tokens):
        if tok(w) in VERB_FORMS:
            return n
    return None


def is_abstract(word):
    t = tok(word)
    if t in ABSTRACT_HEADS:
        return True
    return len(t) > 5 and t.endswith(NOMINAL_SUFFIX)


def names_an_actor(text):
    """Does this span name anybody the reader can picture?"""
    toks = []
    for w in text.split():
        t = tok(w)
        toks.append(t)
        if "'" in t or '’' in t:
            toks.append(re.split(r"['’]", t)[0])
    if any(t in FIRST_SECOND for t in toks):
        return True
    if any(t in ROLE_NOUNS for t in toks):
        return True
    return bool(PROPER_NAME.search(text))


# ======================================================== definite opacity
# Verbatim from the frozen sweep/reference-impl/_shared.py (itself a parity-
# tested copy of the sweep's detector), with one parameter added:
# `suspend_e3_in` names the sentence indices where the postnominal exemption
# does not apply. See fix 1 in the module docstring.
DEF_DET = r'(?:the|its|their|his|her|our|this|that|these|those)'
_BOUND_WORDS = sorted(VERB_FORMS | STOPWORDS | AUX_VERBS,
                      key=lambda w: (-len(w), w))
HEAD_AFTER_WIDE = (
    r"(?=\s*(?:[.,;:!?)»\"'’”—]|$)"
    r"|\s*(?:'s|’s)\b"
    r"|\s+(?:" + '|'.join(re.escape(w) for w in _BOUND_WORDS) + r")\b"
    r"|\s+[a-z][a-z'-]*(?:ed|ing|es|s)\b)")
NP_RE = re.compile(
    r'\b(' + DEF_DET + r')\s+((?:[a-z][a-z-]{2,}\s+){0,2}?)([a-z][a-z-]{2,})\b'
    + HEAD_AFTER_WIDE)
THAT_AFTER_NOUN = re.compile(r"([a-z][a-z'-]*)\s+$")

E1_WORDS = set('first last best worst next previous only same entire whole '
               'main final initial'.split())
E2_HEADS = set('fact result reason idea conclusion point question problem way '
               'case thing kind sort number amount rest end beginning'.split())
E2_NEXT = set('that of why how which to'.split())
E7_HEADS = set('year month day week time morning evening date moment period '
               'afternoon night hour minute'.split())
E8_HEADS = set('reader user system file repo code team world sun government '
               'internet shell terminal screen page document text draft '
               'author writer language english web browser network disk '
               'machine computer keyboard'.split())
PREPOSITIONS = set('of in on at to from by with for about into through during '
                   'before after above below between under over against '
                   'within without across'.split())
RELATIVES = set('that which who whom whose where when'.split())


def _stem(w):
    for suf in ('ing', 'es', 'ed', 's'):
        if w.endswith(suf) and len(w) > len(suf) + 2:
            return w[:-len(suf)]
    return w


def _words_lower(s):
    return [w.strip('.,;:!?()[]"\'—“”').lower()
            for w in s.split() if re.search(r'[A-Za-z0-9]', w)
            and not w.startswith('«')]


def definite_opacity(sentences, k_window=4, suspend_e3_in=()):
    """Definite noun phrases whose referent the text never introduced.

    Returns one finding per definite phrase: UNRESOLVED, resolved, or exempt
    with the exemption's code. `suspend_e3_in` is the set of sentence indices
    where E3 (a preposition or relative follows the noun) does not exempt.
    """
    suspend = set(suspend_e3_in)
    stems_by_sentence = [{_stem(w) for w in _words_lower(s)} for s in sentences]
    findings = []

    for i, s in enumerate(sentences):
        low = s.lower()
        aligned = len(low) == len(s)
        for m in NP_RE.finditer(low):
            det = m.group(1)
            mods = m.group(2).split()
            head = m.group(3)
            if head in STOPWORDS or head in VERB_FORMS or head.endswith('ly'):
                continue
            if det == 'that':
                before = THAT_AFTER_NOUN.search(low[:m.start()])
                if before and before.group(1) not in STOPWORDS \
                        and before.group(1) not in VERB_FORMS \
                        and not before.group(1).endswith(('ed', 'ing')):
                    continue    # relative pronoun, not a determiner
            phrase = s[m.start():m.end()] if aligned else m.group(0)
            rest = low[m.end():].lstrip()
            next_tok = re.match(r"[a-z][a-z'-]*", rest)
            next_tok = next_tok.group(0) if next_tok else ''

            ex = None
            if any(w.endswith('est') or w in E1_WORDS for w in mods):
                ex = 'E1'
            elif head in E2_HEADS and next_tok in E2_NEXT:
                ex = 'E2'
            elif (next_tok in PREPOSITIONS or next_tok in RELATIVES) \
                    and i not in suspend:
                ex = 'E3'
            elif re.match(r',\s+[A-Z]', s[m.end():] if aligned else ''):
                ex = 'E4'
            elif re.search(r'\b(?:is|are|was|were|be|been|being)\s*$',
                           low[:m.start()]):
                ex = 'E5'
            elif aligned and any(c.isupper() for c in s[m.start(2):m.end(3)]):
                ex = 'E6'
            elif head in E7_HEADS:
                ex = 'E7'
            elif head in E8_HEADS or ' '.join(mods + [head]) in E8_HEADS:
                ex = 'E8'
            if ex:
                findings.append({'s': i, 'verdict': 'exempt', 'code': ex,
                                 'phrase': phrase})
                continue

            st = _stem(head)
            resolved = False
            for j in range(max(0, i - k_window), i):
                if st in stems_by_sentence[j]:
                    resolved = True
                    break
                pj = sentences[j].lower()
                if re.search(r'\b(?:a|an|one|some|each|every|another|new)\s+'
                             r'(?:[a-z-]+\s+){0,2}' + re.escape(st), pj):
                    resolved = True
                    break
                if re.search(re.escape(st) + r'[a-z]*\b\s*(?:is|are|means|:|—)',
                             pj):
                    resolved = True
                    break
            if not resolved and re.search(
                    re.escape(head) + r'\s*\([^)]{4,60}\)', low):
                resolved = True
            findings.append({'s': i, 'phrase': phrase,
                             'verdict': 'resolved' if resolved else 'UNRESOLVED'})
    return findings


# ==================================================================== the text
PREFIX_SENTENCES = 3     # the opening window: what the user read before stopping
MAX_SENTENCES = 200      # advisory shapes stop here; a hook has a timeout


class Text(object):
    """One text, read once, with the positions every mechanism shares.

    `title` is a commit's subject line (mono_title), a markdown document's top
    heading, or an HTML page's <title>/<h1>. It is None when the text has none,
    and a title-scoped mechanism then reports nothing rather than guessing.
    """

    def __init__(self, src, mono_title=False, is_html=False):
        self.doc = extract_text(src, is_html=is_html)
        self.raw = self.doc['raw']
        self.is_html = is_html
        self.mono_title = mono_title
        self.sentences = [s for _, s in self.doc['sentences']][:MAX_SENTENCES]

        lines = [l.rstrip() for l in self.raw.splitlines()]
        nonblank = [l.strip() for l in lines if l.strip()]
        self.first_line = nonblank[0] if nonblank else ''

        if is_html:
            self.title = self._html_title()
            self.headings = [self._strip_tags(m.group(2))
                             for m in HTML_HEADING.finditer(self.raw)][:100]
        else:
            heading = ATX_HEADING.match(self.first_line)
            if mono_title:
                self.title = self.first_line
            elif heading:
                self.title = heading.group(2)
            else:
                self.title = None
            self.headings = [ATX_HEADING.match(l).group(2) for l in lines
                             if ATX_HEADING.match(l)][:100]

        # Which extracted sentence IS the title, so the first BODY sentence can
        # be told apart from it.
        self.title_sentence = None
        if self.title is not None and self.sentences:
            head = re.sub(r'\s+', ' ', self.title).strip()
            if re.sub(r'\s+', ' ', self.sentences[0]).strip() == head:
                self.title_sentence = 0
        self.first_body_index = 1 if self.title_sentence == 0 else 0

    def _strip_tags(self, s):
        return re.sub(r'\s+', ' ', html_mod.unescape(
            re.sub(r'<[^>]+>', ' ', s))).strip()

    def _html_title(self):
        m = HTML_TITLE.search(self.raw)
        if m and self._strip_tags(m.group(1)):
            return self._strip_tags(m.group(1))
        for h in HTML_HEADING.finditer(self.raw):
            if h.group(1) == '1' and self._strip_tags(h.group(2)):
                return self._strip_tags(h.group(2))
        return None

    def window(self):
        """The opening: the first PREFIX_SENTENCES sentences, with indices.

        For a commit message the subject line is sentence 0, so the window is
        the subject plus the first two body sentences - what the user described
        reading before they stopped.
        """
        return list(enumerate(self.sentences))[:PREFIX_SENTENCES]

    def positions(self):
        """Every prominent position, in reading order: (kind, text)."""
        out = []
        if self.title is not None:
            out.append(('title', self.title))
        idx = self.first_body_index
        if idx < len(self.sentences):
            out.append(('first_sentence', self.sentences[idx]))
        for h in self.headings:
            if self.title is not None and h.strip() == self.title.strip():
                continue
            out.append(('heading', h))
        return out


# ================================================== mechanism 1: opening referent
def _unbound_pronouns(window):
    """Pronouns in the opening with nothing before them to point at.

    Deliberately generous: it reports a pronoun only when the window offers
    NOTHING it could refer to, which is the case the user described
    ("'returning' to what?" with nothing yet named).
    """
    hits = []
    seen_before = ''
    for idx, sentence in window:
        body = strip_section_label(sentence)
        toks = body.split()
        for i, w in enumerate(toks):
            t = tok(w)
            bare_demo = (i == 0 and BARE_DEMONSTRATIVE.match(body)
                         and t in DEMONSTRATIVES | {'it'})
            if t not in PRONOUN_LEG and not bare_demo:
                continue
            if t == 'it':
                tail = [tok(x) for x in toks[i + 1:i + 8]]
                if tail and tail[0] in ('is', 'was', 'are', 'were'):
                    rest = tail[1:]
                    if 'that' in rest or (rest and (
                            rest[0] in DUMMY_IT_ADJ
                            or rest[0].endswith(DUMMY_IT_ADJ_SUFFIX))):
                        continue          # "it is clear that ..." names nobody
            before = seen_before + ' ' + ' '.join(toks[:i])
            if ANTECEDENT_NP.search(before) or PROPER_NAME.search(before) \
                    or any(tok(x) in FIRST_SECOND for x in before.split()):
                continue
            hits.append(w.strip('.,;:!?'))
        seen_before += ' ' + body
    return hits


def opening_referent(text):
    """Unintroduced definite phrases in the title and in the opening window."""
    window = text.window()
    indices = [i for i, _ in window]
    sentences = [s for _, s in window]
    ti = text.title_sentence

    frozen = definite_opacity(sentences)
    fixed = definite_opacity(sentences, suspend_e3_in=indices)

    def unresolved(findings, only=None):
        return [f['phrase'] for f in findings if f['verdict'] == 'UNRESOLVED'
                and (only is None or f['s'] == only)]

    title_applicable = text.title is not None and ti is not None
    return {
        'title_present': text.title is not None,
        'title_read_as_sentence': title_applicable,
        'title_frozen': unresolved(frozen, ti) if title_applicable else [],
        'title_e3_suspended': unresolved(fixed, ti) if title_applicable else [],
        'window_frozen': unresolved(frozen),
        'window_e3_suspended': unresolved(fixed),
        'window_e3_exempt': [f['phrase'] for f in frozen
                             if f['verdict'] == 'exempt' and f['code'] == 'E3'],
        'unbound_pronouns': _unbound_pronouns(window),
        'window_sentence_count': len(sentences),
    }


# ================================================ mechanism 2: front-loaded framing
N_WORDS_BEFORE_POINT = 6      # the user's own count, round-1 item r1-52
PHRASE_WORD_CAP = 12          # a generosity bound on "phrase, not clause"
COLON_OPENER = re.compile(r'^([^:]{2,200}):\s')
PARENTHETICAL = re.compile(r'\([^)]*\)')
FRONT_CLOSER = re.compile(r'[,:;—]|--')
INDEFINITE_PRONOUNS = set("""nothing something anything everything nobody
somebody anybody everybody none""".split())
DEFINITE_OPENER = re.compile(r'^(?:the|this|that|these|those|its|their)\b', re.I)


def _colon_span(body):
    """The phrase a sentence puts in front of its colon, if it is a phrase."""
    m = COLON_OPENER.match(body)
    if not m:
        return None
    span = m.group(1)
    n = len(words(span))
    if n < 2 or n > PHRASE_WORD_CAP:
        return None
    probe = PARENTHETICAL.sub(' ', span)      # a gloss inside an NP is still NP
    if first_finite_verb(probe.split()) is not None:
        return None
    if names_an_actor(probe):
        return None
    return span.strip(), probe


def _shape_a(body):
    """Nominal framing phrase, then a colon, then the point."""
    got = _colon_span(body)
    if not got:
        return None
    span, probe = got
    heads = [tok(w) for w in probe.split() if is_abstract(w)]
    if not heads:
        return None
    return {'shape': 'nominal_framing_colon', 'span': span,
            'words_before_point': len(words(span))}


def _shape_d(body):
    """A definite phrase used as a frame: "The result: ...".

    The advisory-only fix from ROUND2-ANALYSIS.md F.4. Shape A misses it
    because "result" is not an abstract head, and deciding that it is one while
    reading the accepted texts would be fitting; this reports the definite
    determiner instead, which is the user's own rule (define it or name it in
    full) applied to a framing phrase.
    """
    got = _colon_span(body)
    if not got:
        return None
    span, probe = got
    if not DEFINITE_OPENER.match(probe.strip()):
        return None
    if _shape_a(body):
        return None                    # already reported as the abstract shape
    return {'shape': 'definite_framing_colon', 'span': span,
            'words_before_point': len(words(span))}


def _fronting_marker(first_word):
    t = tok(first_word)
    if t in INDEFINITE_PRONOUNS:
        return None                    # a subject, not fronted material
    if t in SUBORDINATORS or t in FRONTING_PREPOSITIONS:
        return 'subordinator or preposition'
    if len(t) > 4 and t.endswith(('ing', 'ed')):
        return 'participle'
    return None


def _shape_b(body):
    """Fronted material that takes six or more words to reach the point."""
    toks = body.split()
    if not toks or not _fronting_marker(toks[0]):
        return None
    n = 0
    for i, w in enumerate(toks):
        if i and tok(w) in VERB_FORMS:
            break                              # the point: a finite verb
        n += 1
        if FRONT_CLOSER.search(w):
            break                              # the point: the fronting comma
    span = ' '.join(toks[:n])
    if len(words(span)) < N_WORDS_BEFORE_POINT:
        return None
    return {'shape': 'fronted_clause', 'span': span.strip(),
            'words_before_point': len(words(span))}


def _shape_c(body):
    """Abstract heads stacked in front of the first finite verb."""
    toks = body.split()
    v = first_finite_verb(toks)
    span_toks = (toks[:v] if v is not None else toks)[:PHRASE_WORD_CAP]
    if len(span_toks) < 2:
        return None
    span = ' '.join(span_toks)
    if names_an_actor(span):
        return None
    if len([tok(w) for w in span_toks if is_abstract(w)]) < 2:
        return None
    return {'shape': 'abstract_np_chain', 'span': span.strip(),
            'words_before_point': len(words(span))}


SHAPES = (_shape_a, _shape_b, _shape_c, _shape_d)


def front_loaded_framing(text):
    """Framing phrases, split by shape and by position."""
    opener_indices = {i for i in (text.title_sentence, text.first_body_index)
                      if i is not None}
    matches = []
    for i, sentence in enumerate(text.sentences):
        body = strip_section_label(sentence)
        for shape in SHAPES:
            hit = shape(body)
            if hit:
                hit['position'] = ('opener' if i in opener_indices else 'body')
                matches.append(hit)
    return {
        'colon_opener': [m for m in matches
                         if m['position'] == 'opener'
                         and m['shape'] == 'nominal_framing_colon'],
        'fronted_opener': [m for m in matches
                           if m['position'] == 'opener'
                           and m['shape'] in ('fronted_clause',
                                              'abstract_np_chain')],
        'definite_colon': [m for m in matches
                           if m['shape'] == 'definite_framing_colon'],
        'body': [m for m in matches if m['position'] == 'body'
                 and m['shape'] != 'definite_framing_colon'],
    }


# ================================================ mechanism 3: positional aphorism
# Eight patterns copied verbatim from the 2026-08-15 proto/linter.py
# APHORISM_PATTERNS (the set config-freeze.json demoted); the ninth was added
# 2026-08-21 from the user's own wording, because the frozen is-X-not-Y needs a
# copula and the shape they quoted is the bare contrast.
APHORISM_PATTERNS = {
    'is-X-not-Y':   re.compile(r'\b(?:is|are|was|were)\s+[^.,;]{3,40},\s*not\s+'),
    'not-because':  re.compile(r'\bnot because\b', re.I),
    'the-very':     re.compile(r'\bthe very\s+\w+', re.I),
    'exactly-when': re.compile(r'\bexactly\s+(?:when|where|what|how)\b', re.I),
    'turns-into':   re.compile(r'\bturns?\s+\w[\w\s-]{0,35}\binto\b'),
    'never-always': re.compile(r'^(?:Never|Always)\b'),
    'that-is-the':  re.compile(r'\bThat is (?:not )?(?:the|what|why|how)\b'),
    'em-dash-flip': re.compile(r'—\s*(?:it|that|this)\s+(?:is|was)\b'),
    'x-not-y-contrast': re.compile(
        r',\s*not\s+(?:just|only|merely|simply|the)?\s*\S'),
}


def _aphorism_matches(line):
    return [name for name, pat in sorted(APHORISM_PATTERNS.items())
            if pat.search(line)]


def positional_aphorism(text):
    """The quotable contrast, counted apart by position.

    The title is reported alone because that is the only position round 2
    supports: an accepted round-1 commit carries the same construction in body
    text, doing clarifying work.
    """
    out = {'title': [], 'prominent_other': [], 'body': []}
    prominent_lines = set()
    for kind, line in text.positions():
        prominent_lines.add(re.sub(r'\s+', ' ', line).strip())
        key = 'title' if kind == 'title' else 'prominent_other'
        out[key].extend(_aphorism_matches(line))
    for sentence in text.sentences:
        if re.sub(r'\s+', ' ', sentence).strip() in prominent_lines:
            continue
        out['body'].extend(_aphorism_matches(strip_section_label(sentence)))
    return out


# ======================================================== signals and principles
# One entry per signal: how it is read off the mechanisms, and - for the ones
# that may block - the principle a denial teaches. The message never names the
# span: telling a writer which words to change buys lexical compliance, which
# is the failure this gate exists to prevent.
def raw_signals(text):
    """Every signal for one Text, as the list of things each one found.

    Public because the validation harness scores these lists directly; the gate
    reads them through `analyze`, which applies the tiers.
    """
    ref = opening_referent(text)
    fram = front_loaded_framing(text)
    aph = positional_aphorism(text)
    return {
        'opening_referent.title': ref['title_frozen'],
        'opening_referent.title_e3_suspended': ref['title_e3_suspended'],
        'opening_referent.opening_window': ref['window_frozen'],
        'opening_referent.opening_window_e3_suspended': ref['window_e3_suspended'],
        'opening_referent.unbound_pronoun': ref['unbound_pronouns'],
        'front_loaded_framing.colon_opener': fram['colon_opener'],
        'front_loaded_framing.fronted_opener': fram['fronted_opener'],
        'front_loaded_framing.definite_colon': fram['definite_colon'],
        'front_loaded_framing.body': fram['body'],
        'positional_aphorism.title': aph['title'],
        'positional_aphorism.prominent_other': aph['prominent_other'],
        'positional_aphorism.body': aph['body'],
    }


ALL_SIGNALS = (
    'opening_referent.title',
    'opening_referent.title_e3_suspended',
    'opening_referent.opening_window',
    'opening_referent.opening_window_e3_suspended',
    'opening_referent.unbound_pronoun',
    'front_loaded_framing.colon_opener',
    'front_loaded_framing.fronted_opener',
    'front_loaded_framing.definite_colon',
    'front_loaded_framing.body',
    'positional_aphorism.title',
    'positional_aphorism.prominent_other',
    'positional_aphorism.body',
)

# The candidates the validation harness scores. They are the four mechanisms
# round 2 left standing at a position the user actually named: the title leg of
# opening-referent failure (in both E3 readings), the opening window with the
# E3 fix, the framing colon in an opener, and the contrast in a title. Nothing
# outside this tuple can ever block, whatever the harness says about it.
CANDIDATE_SIGNALS = (
    'opening_referent.title',
    'opening_referent.title_e3_suspended',
    'opening_referent.opening_window',
    'opening_referent.opening_window_e3_suspended',
    'front_loaded_framing.colon_opener',
    'positional_aphorism.title',
)

# Everything else is advisory by construction, not by measurement: a body-
# position framing phrase, a body contrast, the definite-colon fix and the
# inert pronoun leg were never pre-registered at a position the labels support,
# so no false-positive result can promote them.
ADVISORY_ONLY = tuple(n for n in ALL_SIGNALS if n not in CANDIDATE_SIGNALS)

# A signal is applicable to a text only when the text has the position it
# reads; a title-scoped signal cannot be quiet or loud about a text with no
# title. The harness reports applicability so a vacuous pass is visible as one.
TITLE_SCOPED = ('opening_referent.title', 'opening_referent.title_e3_suspended',
                'positional_aphorism.title')

PRINCIPLES = {
    'opening_referent.title': (
        'the title names something the reader has not been told about yet',
        'a title says who does what to which part, in words that stand alone'),
    'opening_referent.title_e3_suspended': (
        'the title names something the reader has not been told about yet',
        'a title says who does what to which part, in words that stand alone'),
    'opening_referent.opening_window': (
        'the opening does not establish who or what the text is about',
        'the first sentences name the actor and define every thing they '
        'mention, or refer to it in full'),
    'opening_referent.opening_window_e3_suspended': (
        'the opening does not establish who or what the text is about',
        'the first sentences name the actor and define every thing they '
        'mention, or refer to it in full'),
    'front_loaded_framing.colon_opener': (
        'a framing phrase delays the point of the opening sentence',
        'the point arrives first, and any qualification follows it'),
    'positional_aphorism.title': (
        'the title carries a rhetorical contrast instead of a statement',
        'a title states what is true and leaves out what is not'),
}

SKILL_PATH = 'plugins/harness/skills/writing-guard/SKILL.md'

# --------------------------------------------------------------------------
# GENERATED BLOCK - do not edit by hand. Regenerate with:
#     python3 tests/writing-guard-fp-validation.py --write
# The harness runs every candidate signal over the texts the user accepted and
# qualifies a signal for blocking only when it fires on none of them. The gate
# reads the result; it never recomputes it.
# BEGIN GENERATED
BLOCKING_SIGNALS = (
    'opening_referent.title',
    'opening_referent.title_e3_suspended',
    'front_loaded_framing.colon_opener',
    'positional_aphorism.title',
)
FP_VALIDATION = {
    "front_loaded_framing.colon_opener": {
        "accepted_texts_applicable": 3,
        "accepted_texts_total": 3,
        "fires_on_accepted": [],
        "fires_on_rejected": "1 of 30",
        "tier": "blocking"
    },
    "opening_referent.opening_window": {
        "accepted_texts_applicable": 3,
        "accepted_texts_total": 3,
        "fires_on_accepted": [
            "r1-27/r2-03",
            "r2-11"
        ],
        "fires_on_rejected": "25 of 30",
        "tier": "advisory"
    },
    "opening_referent.opening_window_e3_suspended": {
        "accepted_texts_applicable": 3,
        "accepted_texts_total": 3,
        "fires_on_accepted": [
            "r1-27/r2-03",
            "r2-11"
        ],
        "fires_on_rejected": "29 of 30",
        "tier": "advisory"
    },
    "opening_referent.title": {
        "accepted_texts_applicable": 1,
        "accepted_texts_total": 3,
        "fires_on_accepted": [],
        "fires_on_rejected": "5 of 30",
        "tier": "blocking"
    },
    "opening_referent.title_e3_suspended": {
        "accepted_texts_applicable": 1,
        "accepted_texts_total": 3,
        "fires_on_accepted": [],
        "fires_on_rejected": "6 of 30",
        "tier": "blocking"
    },
    "positional_aphorism.title": {
        "accepted_texts_applicable": 1,
        "accepted_texts_total": 3,
        "fires_on_accepted": [],
        "fires_on_rejected": "2 of 30",
        "tier": "blocking"
    }
}
# END GENERATED
# --------------------------------------------------------------------------


def analyze(src, mono_title=False, is_html=False):
    """Every signal for one text, split into the tier that may block and the
    tier that may not."""
    text = Text(src, mono_title=mono_title, is_html=is_html)
    raw = raw_signals(text)
    fired = sorted(name for name, hits in raw.items() if hits)
    return {
        'blocking': [n for n in fired if n in BLOCKING_SIGNALS],
        'advisory': [n for n in fired if n not in BLOCKING_SIGNALS],
        'counts': {name: len(hits) for name, hits in raw.items()},
        'title_present': text.title is not None,
        'sentences_read': len(text.sentences),
    }


def deny_message(blocking):
    """What a denied writer is told: the principle, the target, the skill.

    Never the span, never its position, never the count of them. A writer
    handed the failing words edits those words and ships the same text; a
    writer handed the principle has to read their own opening again.
    """
    principles, targets = [], []
    for name in blocking:
        principle, target = PRINCIPLES[name]
        if principle not in principles:
            principles.append(principle)
            targets.append(target)
    if not principles:
        return ''
    return ('Blocked by the writing guard.\n'
            'What a reader meeting this cold runs into: %s.\n'
            'Write the passage again so that %s.\n'
            'The rules, and the one register that has passed a reader, are in '
            '%s. Work from them and write it fresh rather than editing out '
            'whatever you think this gate objected to - it names no phrase on '
            'purpose, because swapping those words is not the same as writing '
            'something a reader can follow.'
            % ('; '.join(principles), '; '.join(targets), SKILL_PATH))


# ========================================================================= CLI
def main(argv):
    argv = list(argv)
    mono = '--mono-title' in argv
    argv = [a for a in argv if a != '--mono-title']
    if len(argv) != 1:
        sys.stderr.write('usage: writing_guard_detectors.py <file> '
                         '[--mono-title]\n')
        return 2
    path = argv[0]
    with open(path, encoding='utf-8', errors='replace') as fh:
        src = fh.read()
    out = analyze(src, mono_title=mono,
                  is_html=path.lower().endswith(('.html', '.htm')))
    out['deny_message'] = deny_message(out['blocking'])
    print(json.dumps(out, ensure_ascii=False, indent=1))
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
